# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8e0b167e7f2974363bd7b000d07df839699287f33252f7d30f152dcb650c1debbc458ee4a497662c740720e99746bdeb341a764a48dbb6e4d171bc6a1bee56

test:
  secret_key_base: f52c1b859cc95b5a3dbe2381122e10e80a6c69faa4ffa768c2083b95e79b445dbea20b454aecc70afbb1f4bc9e4f50477098258011e292306f7809961ecba1c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
